### ISSUE TITLE
Output validation?

### ISSUE THREAD

**Issue by zaaack** [chentsulin/koa-context-validator#10]

**Comment by zaaack** [comment]
I think I might understand how to validate the output...

**Comment by chentsulin** [comment]
I am not sure we should support this feature just because hapi supports it. I will encourage keep assigning consistent output instead of relying on output validation.

**Comment by chentsulin** [comment]
IMO using static type checking with flowtype or typescript is more efficient than dynamic type checking with output validation, so closing this issue.

**Comment by zaaack** [comment]
@chentsulin Ok, I want to integrate the validation with swagger,  and flowtype or typescript are not easy to do this. I'll just create a built-in Joi validation.
