### ISSUE TITLE
joi dependency outdated

### ISSUE THREAD

**Issue by QuentinRoy** [chentsulin/koa-context-validator#17]
koa-context-validator uses joi@10.6.0 that is no longer maintained. As a result, I get the following warning when installing:

> warning koa-context-validator > joi@10.6.0: This version is no longer maintained. Please upgrade to the latest version.

Time to update?

**Comment by wertlex** [comment]
Seems like this issue could be closed. `koa-context-validator` is using `joi` 17.3.+ : https://github.com/chentsulin/koa-context-validator/blob/master/package.json#L29

**Comment by QuentinRoy** [comment]
I haven't checked the latest version. I am happy to close if the issue is resolved.

**Comment by tw0517tw** [comment]
In 0.5.0 we've updated the `Joi` dependency. There is a breaking change due to Joi upgrade. Make sure you check our changelog when upgrading.
