### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by GavinOsborn** [chentsulin/koa-context-validator#6]
Your library looks v.interesting.
If I needed to add a custom `project specific` validation rule how would I do that?
eg: A rule to check to see if a value already exists in our database?

**Comment by chentsulin** [comment]
`joi` does not support async validate functions now, so you need to implement async validate by yourself at this moment. 
See further discuss: https://github.com/hapijs/joi/issues/631 https://github.com/hapijs/joi/issues/577

**Comment by GavinOsborn** [comment]
Sure, a database check was merely an example.
What if I wanted to make a rule that didn't require async execution?

**Comment by kolpav** [comment]
I assume you are using `koa-router`. You can have as many middlewares on your route as you want `koa-context-validator` is just one of them.
```javascript
import Router from 'koa-router'
const router = new Router()
router.get(
  '/:id',
  validator({ params: object().keys({ id: string().required() }) }),
  async (ctx, next) => {
    const isValid = await isValid(ctx)
    if (!isValid) ctx.throw('Request is not valid for some reason')
    await next()
  },
  async (ctx, next) => {
    ctx.body = await getFromDb(ctx.params.id)
  }
)
```

**Comment by mdluo** [comment]
@kolpav Where is the `isValid` comes from?

**Comment by chentsulin** [comment]
FYI, 
with latest Joi, now we can have something like this: 

```js
import Koa from 'koa';
import validator, { Joi } from 'koa-context-validator';

const lookup = async (username) => {
  const user = await db.get('user', username);
  if (!user) {
    throw new Error('Invalid username');
  }
};

app.use(
  validator({
    body: Joi.object().keys({
      username: Joi.string().external(lookup),
    }),
  }),
);
```

https://github.com/chentsulin/koa-context-validator#asynchronous-operations
